name: neovim
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - greenlet
  - psutil
  - black
  - pynvim
  - c-compiler
  - nodejs  #then, npm install -g neovim
  - ruby  #then, gem install neovim
  - bat
  - ripgrep
  - fzf
  - fd-find
  - protobuf=3.20
  - pip:
    - neovim-remote
