name: neovim
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - greenlet
  - psutil
  - black
  - pynvim
  - compilers
  - nodejs  #then, npm install -g neovim
  - ruby  #then, gem install neovim
  - bat
  - ripgrep
  - pip:
    - neovim-remote
    - iterm2
    - pyobjc
