name: neovim
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - greenlet
  - psutil
  - black
  - nodejs  #then, npm install -g neovim
  - pip:
    - msgpack
    - neovim-remote
    - pynvim
