name: neovim
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  - greenlet
  - psutil
  - black
  - pynvim
  - compilers
  - nodejs  #then, npm install -g neovim
  - ruby  #then, gem install neovim
  - bat
  - ripgrep
  - fd-find
  - protobuf=3.20
  - rust
  - luarocks
  - pip:
    - neovim-remote
