#!/usr/bin/env bash
git rev-parse --is-inside-work-tree >& /dev/null
if [ $? -eq 0 -a $(git rev-parse --show-toplevel)/bin/python ]; then
    #echo $(git rev-parse --show-toplevel)/bin/python "$@"
    $(git rev-parse --show-toplevel)/bin/python "$@"
else
    #echo python "$@"
    python "$@"
fi
