#!/usr/bin/env bash
# to debug, uncomment the lines below
#exec 3>&1 4>&2
#trap 'exec 2>&4 1>&3' 0 1 2 3
#exec 1>python.out 2>&1
git rev-parse --is-inside-work-tree >& /dev/null
if [ $? -eq 0 -a $(git rev-parse --show-toplevel)/bin/python ]; then
    #echo "Executing:" $(git rev-parse --show-toplevel)/bin/python "$@"
    #$(git rev-parse --show-toplevel)/bin/python "$@" >&3
    $(git rev-parse --show-toplevel)/bin/python "$@"
else
    #echo "Executing:" python "$@"
    #python "$@" >&3
    python "$@"
fi
