# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Longer time outs
command_timeout = 1000  # ms

# Inserts a blank line between shell prompts
add_newline = false

format = """
$fill\
$line_break\
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$conda\
$python\
$package\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$container\
$shell\
$character"""

# Set "anjos" as custom color palette
palette = "custom"

[palettes.custom]
background = "#000000"
time = "#ffffff"
conda = "#ff9300"
python = "#99cc00"
package = "#927735"
directory = "blue"
cmd = "yellow"
git_branch = "purple"
git_status = "red"

[time]
disabled = false
format = "[$time ]($style)"
style = "bold fg:time bg:background"
time_format = "%H:%M"

[conda]
style = "bold fg:conda bg:background"
format = "[$symbol$environment ]($style)"
ignore_base = false

[python]
symbol = "🐍"
style = "bold fg:python bg:background"
format = "[$symbol $version ]($style)"

[package]
disabled = true
style = "bold fg:package bg:background"

[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic fg:directory bg:background"
repo_root_style = "bold italic fg:directory bg:background"
repo_root_format = "[$before_root_path]($style)[{$repo_root}]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
min_time = 100
show_milliseconds = false
disabled = false
style = "bold italic fg:cmd bg:background"
format = "[⏱️ $duration]($style)"

[git_branch]
symbol = " "
style = "bold fg:git_branch bg:background"
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "bold fg:git_status bg:background"

[lua]
disabled = true
format = "[$symbol ($version )]($style)"

[fill]
symbol = "─"
style = "fg:#1f1f1f"
